{{- if .Values.jobServiceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.jobServiceAccount.name }}
  labels:
    {{- include "dma.labels" . | nindent 4 }}
    {{- with .Values.chartLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-8"
    {{- with .Values.chartAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.jobServiceAccount.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.jobServiceAccount.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}