{{- if (eq .Values.global.cloudProvider "aws") }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storage.storageClass | quote }}
  labels:
    {{- include "worker-temporal.labels" . | nindent 4 }}
    {{- with .Values.chartLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.chartAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
provisioner: "kubernetes.io/aws-ebs"
reclaimPolicy: "Delete"
parameters:
  encrypted: "true"
  fsType: "ext4"
  type: "gp3"
allowVolumeExpansion: true
volumeBindingMode: "WaitForFirstConsumer"
{{- end }}
{{- if (eq .Values.global.cloudProvider "gcp") }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storage.storageClass | quote }}
  labels:
    {{- include "worker-temporal.labels" . | nindent 4 }}
    {{- with .Values.chartLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.chartAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
provisioner: "kubernetes.io/gce-pd"
reclaimPolicy: "Delete"
parameters:
  type: "pd-standard"
  fsType: "ext4"
allowVolumeExpansion: true
volumeBindingMode: "WaitForFirstConsumer"
{{- end }}
{{- if (eq .Values.global.cloudProvider "azure") }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.storage.storageClass | quote }}
  labels:
    {{- include "worker-temporal.labels" . | nindent 4 }}
    {{- with .Values.chartLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.chartAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
provisioner: "disk.csi.azure.com"
reclaimPolicy: "Delete"
parameters:
  skuname: "StandardSSD_LRS"
  fsType: "ext4"
allowVolumeExpansion: true
volumeBindingMode: "WaitForFirstConsumer"
{{- end }}
