apiVersion: v1
kind: Service
metadata:
  name: {{ include "datafold.kept.server" . }}
  labels:
    {{- include "kept.labels" . | nindent 4 }}
    {{- with .Values.chartLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.chartAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ include "datafold.kept.port" . }}
      targetPort: kept
      protocol: TCP
  selector:
    {{- include "kept.selectorLabels" . | nindent 4 }}
